package com.lh.kete.views.main;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

public class MainForm implements MainView {
    private JPanel mainPanel;
    private RTextScrollPane textAreaScrollPane;
    private RSyntaxTextArea textArea;
    private JButton preview;
    private JMenuBar menuBar;

    private MainPresenter mPresenter;
    private ActionListener mPreviewListener;

    public MainForm() {
        // Construct listener & component
        mPresenter = new PresenterImpl(this);
        mPreviewListener = e -> mPresenter.onPreview();
        $$$setupUI$$$();

        // After installing component, add listener for remaining component.
        preview.addActionListener(mPreviewListener);
    }

    @Override
    public Component getComponent() {
        return mainPanel;
    }

    @Override
    public String getCurrentText() {
        return textArea.getText();
    }

    private void createUIComponents() {
        textArea = new RSyntaxTextArea();
        textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JSON_WITH_COMMENTS);
        textArea.setCodeFoldingEnabled(true);
        textArea.setHighlightCurrentLine(false);
        textAreaScrollPane = new RTextScrollPane(textArea);
        menuBar = new JMenuBar();

        //Build the first menu.
        JMenu menu = new JMenu("Menu");
        menuBar.add(menu);

        //a group of JMenuItems
        JMenuItem menuItem = new JMenuItem("Preview",
                KeyEvent.VK_P);
        menuItem.setAccelerator(KeyStroke.getKeyStroke(
                KeyEvent.VK_P, InputEvent.CTRL_MASK));
        menu.add(menuItem);

        // Add Listener
        menuItem.addActionListener(mPreviewListener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        preview = new JButton();
        preview.setText("Preview");
        mainPanel.add(preview, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        mainPanel.add(textAreaScrollPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        textAreaScrollPane.setViewportView(textArea);
        mainPanel.add(menuBar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
